FROM node

WORKDIR /app

COPY package.json .
RUN rm -rf package-lock.json node_modules && npm i

COPY . .

## EXPOSE [Port you mentioned in the vite.config file]

EXPOSE 8080

CMD ["npm", "run", "dev"]
